-- TRIGGERS PARA ALMACENAR UN PRESTAMO EN EL HISTORIAL DE TRANSACCIONES
CREATE OR REPLACE TRIGGER TRG_AFTER_INSERT_PRESTAMO
    AFTER INSERT ON PRESTAMO
    FOR EACH ROW
BEGIN
    INSERT INTO HISTORIAL_TRANSACCION (FECHA_TRANSACCION, TIPO_TRANSACCION, ID_USUARIO, ISBN, ID_EMPLEADO)
    VALUES (SYSDATE, 'PRESTAMO', :NEW.ID_USUARIO, :NEW.ISBN, :NEW.ID_EMPLEADO);
END;
/

-- TRIGGER PARA ALMACENAR LA DEVOLUCION DE UN PRESTAMO EN EL HISTORIAL DE TRANSACCIONES
CREATE OR REPLACE TRIGGER TRG_AFTER_UPDATE_PRESTAMO
    AFTER UPDATE OF FECHA_DEVOLUCION ON PRESTAMO
    FOR EACH ROW
    WHEN (NEW.FECHA_DEVOLUCION IS NOT NULL)
BEGIN
    INSERT INTO HISTORIAL_TRANSACCION (FECHA_TRANSACCION, TIPO_TRANSACCION, ID_USUARIO, ISBN, ID_EMPLEADO)
    VALUES (SYSDATE, 'DEVOLUCION', :NEW.ID_USUARIO, :NEW.ISBN, :OLD.ID_EMPLEADO);
END;
/

-- TRIGGER PARA CREAR TARJETA DE BIBLIOTECA AL REGISTRAR UN NUEVO USUARIO YA SEA ESTUDIANTE O PROFESOR
CREATE OR REPLACE TRIGGER TRG_AFTER_INSERT_USUARIO
    AFTER INSERT ON USUARIO
    FOR EACH ROW
BEGIN
    INSERT INTO TARJETA_BIBLIOTECA (ID_TARJETA, FECHA_EXPEDICION, FECHA_EXPIRACION)
    VALUES (:NEW.ID_USUARIO, SYSDATE, ADD_MONTHS(SYSDATE, 12));
END;
/

-- ver los triggers
SELECT trigger_name, table_name, triggering_event, status
FROM user_triggers;
